global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'uptime-monitor'
    static_configs:
      - targets: ['uptime-monitor:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']